name: Build Worker

on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ybojko/voting-app-ci/.github/workflows/build.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      service-name: worker
      context: .
      platforms: linux/amd64,linux/arm64
    secrets:
      GIT_OPS_TOKEN: ${{ secrets.GIT_OPS_TOKEN }}
